QnA_app/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views

app_name = 'QnA_app'

urlpatterns = [
    # base_views.py
    path('', base_views.QnA_main, name="QnA_main"),
    path('detail/<int:pk>', base_views.detail, name="QnA_detail"),

    # question_views.py
    path('post/', question_views.post, name="post"),
    path('question/update/<int:pk>', question_views.question_update, name="question_update"),
    path('delete/<int:pk>', question_views.question_delete, name="question_delete"),

    # answer_views.py
    path('answer/<int:pk>', answer_views.answer_create, name='answer_create'),
    path('answer/update/<int:answer_id>/', answer_views.answer_update, name='answer_update'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:pk>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'), 
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

basic/urls.py
from django.contrib import admin
from django.urls import path, include
import main_app.urls

import login_app.urls

import QnA_app.urls
from QnA_app.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(main_app.urls)),
    
    path('', base_views.QnA_main, name="QnA_main"),
    path('QnA/', include(QnA_app.urls)),
    path('common/', include(login_app.urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('excurri/', views.excurri, name='excurri'),
    path('contest/', views.contest, name='contest'),
    path('dsum/', views.dsum, name='dsum'),
    path('tutoring/', views.tutoring, name='tutoring'),
]

main_app/models.py
from django.db import models

# Create your models here.

class Write_list(models.Model):
   title = models.CharField(max_length=100, null=False)
   image = models.ImageField(upload_to='images/')
   created_date = models.DateTimeField(auto_now_add=True)
   end_date = models.DateTimeField()
   hits = models.PositiveIntegerField(default = 0)
   link = models.URLField("Site URL", null=False, blank=False, max_length=200)

   def __str__(self):
      return self.title
   
   @property
   def counter(self):
      self.hits = self.hits + 1
      self.save()

QnA_app/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import QnaModel

def QnA_main(request):
    """
    paginator
    """
    # 입력 parameter
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recent':
        boards = QnaModel.objects.order_by('-created_date')
    elif so == 'author':
        boards = QnaModel.objects.order_by('author', '-created_date')
    else:  # popular
        boards = QnaModel.objects.order_by('-hits')
    
    #------------------------------------------------------------------------#
    # 검색
    if kw:
            boards = boards.filter(
                Q(title__icontains=kw)  # 제목검색
                #Q(content__icontains=kw) |  # 내용검색
                #Q(author__username__icontains=kw) |  # 질문 글쓴이검색
                #Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색 
            ).distinct()
    #------------------------------------------------------------------------#

    # 페이징 처리
    paginator = Paginator(boards, 10) # 게시글 10개
    page_obj = paginator.get_page(page)

    context = {'boards': page_obj, 'page': page, 'kw': kw, 'so': so}  # page와 search가 추가되었다.
    # boards = QnaModel.objects.all()
    return render(request, 'QnA/QnA_main.html', context)

def detail(request, pk):
    try:
        boards = get_object_or_404(QnaModel, pk=pk)
    except QnaModel.DoesNotExist:
        raise Http404("Does not exist!")
    boards.counter
    return render(request, 'QnA/QnA_detail.html', {'boards': boards})

main_app/views.py
from django.shortcuts import render
from .models import Write_list
from django.core.paginator import Paginator
# Create your views here.

def test(request):
    return render(request, 'test.html')
    
def main(request):
    WriteDsum = Write_list.objects
    return render(request, 'main/main.html', {'WriteDsum': WriteDsum})

def excurri(request):
    return render(request, 'excurri.html')

def contest(request):
    return render(request, 'contest.html')

def dsum(request):

    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
# ---------------------------------------------------------------------------- #    

    # 조회
    WriteDsum = Write_list.objects.order_by('-created_date')

    # 페이징처리
    paginator = Paginator(WriteDsum, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context_dsum = {'WriteDsum': page_obj}
    return render(request, 'd-sum/dsum.html', context_dsum)
    
def tutoring(request):
    return render(request, 'tutoring.html')

main_app/templates/base.html
<!DOCTYPE html><!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Tue Dec 29 2020 01:04:46 GMT+0000 (Coordinated Universal Time)  -->

{% load static %}
<html data-wf-page="5fdf5b16ab6df32d7c9b9f8f" data-wf-site="5fdf5b16ab6df35ee79b9f8e">
<head>
  <meta charset="utf-8">
  <title>SandBox_전자 및 정보공학과 비교과 웹 고려대학교 세종</title>
  <meta content="고려대학교 세종캠퍼스 전자 및 정보공학과 비교과 웹 페이지입니다." name="description">
  <meta content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png" property="og:image">
  <meta content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png" property="twitter:image">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href="{% static 'css/normalize.css'%}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/final-2c3dd8-a747bae44c98-22507a1374e85.webflow.css'%}" rel="stylesheet" type="text/css">
  <link href="{% static 'images/favicon.png'%}" rel="shortcut icon" type="image/x-icon">
  <link href="{% static 'images/webclip.png'%}" rel="apple-touch-icon"><!--  Twitter Card data  -->
  
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="http://ecommerce-ui-kit-prospero.webflow.io/">
  <meta name="twitter:title" content="Prospero UI Kit - Webflow Ecommerce UI Kit">
  <meta name="twitter:description" content="Prospero UI Kit is a clean, modular — and free — UI kit for ecommerce. Get the pieces you need to build and launch a polished store in Webflow.">
  <meta name="twitter:creator" content="@webflow">
  <meta name="twitter:image" content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png">
  <!--  Open Graph data  -->
  <meta property="og:title" content="Prospero UI Kit - Webflow Ecommerce UI Kit">
  <meta property="og:type" content="article">
  <meta property="og:url" content="http://ecommerce-ui-kit-prospero.webflow.io/">
  <meta property="og:image" content="https://uploads-ssl.webflow.com/5d56cc02847b584c88980881/5dc3fab751595bfc80a9c136_OG%20Image%20Kit.png">
  <meta property="og:description" content="Prospero UI Kit is a clean, modular — and free — UI kit for ecommerce. Get the pieces you need to build and launch a polished store in Webflow.">
  <meta property="og:site_name" content="Prospero UI Kit">
</head>

<body>

<div data-collapse="medium" data-animation="default" data-duration="400" data-easing2="ease-in-out-circ" data-easing="ease-out-circ" id="navigation" role="banner" class="navbar w-nav">
    <div class="nav-kit-wrap"><img src="{% static 'images/crimson1positive.gif'%}" loading="lazy" width="23" alt="" class="image-2">
      <a href="{% url 'main' %}" class="prospero-brand w-nav-brand">
        <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
        <div class="prospero-nav-logo under"><strong>KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
      </a>
      <div class="nav-kit-divider"></div>
    </div>

    <nav role="navigation" class="nav-menu w-nav-menu">
      <div class="dropdowns-wrap">
        <div data-hover="1" data-delay="0" class="dropdown w-dropdown">
          <div class="dropdown-toggle w-dropdown-toggle">
            <div class="dropdown-wrap">
              <div class="prospero-link">전체비교과</div><img src="{% static 'images/Dropdown-Arrow2x.svg'%}" alt="" class="kit-arrow-dropdown">
            </div>
          </div>
          <nav class="dropdown-list w-dropdown-list">
            <div>
              <a href="{% url 'dsum' %}" class="dropdown-link w-dropdown-link">d-sum</a>
              <a href="{% url 'QnA_app:QnA_main'%}" class="dropdown-link w-dropdown-link">전공1000제</a>
              <a href="{% url 'tutoring' %}" class="dropdown-link w-dropdown-link">전공튜터링</a>
              <a href="#" class="dropdown-link w-dropdown-link">공모전</a>
            </div>
          </nav>
        </div>
        <div data-hover="1" data-delay="0" class="dropdown w-dropdown">
          <div class="dropdown-toggle w-dropdown-toggle">
            <div class="dropdown-wrap">
              <div class="prospero-link">기타</div>
                <img src="{% static 'images/Dropdown-Arrow2x.svg'%}" alt="" class="kit-arrow-dropdown">
              </div>
            </div>
            <nav class="dropdown-list w-dropdown-list">
              <div>
                <a href="#" class="dropdown-link w-dropdown-link">Co-Working</a>
                <a href="#" class="dropdown-link w-dropdown-link">과학문화활동</a>
                <a href="#" class="dropdown-link w-dropdown-link">Data Refinery Center</a>
              </div>
              <div>
                <a href="#" class="dropdown-link w-dropdown-link">sFGR 링크 연구회</a>
                <a href="#" class="dropdown-link w-dropdown-link">캡스톤 프로그램</a>
                <a href="#" class="dropdown-link w-dropdown-link">Super Computing Center</a>
              </div>
            </nav>
          </div>
        </div>
      </nav>
      <div class="kit-nav-buttons-wrap">
        {% if user.is_authenticated %}
        <h5>환영합니다. {{ user.username }}&nbsp;&nbsp;</h5>
          <a class="button-small kit-download-menu w-inline-block" href="{% url 'login_app:logout' %}" >로그아웃</a>
        {% else %}
          <a class="button-small kit-download-menu w-inline-block" href="{% url 'login_app:login' %}">로그인</a>
        {% endif %}
        <div data-w-id="ae2b4f16-c826-fbf0-1743-c29e48bda8e9" class="menu-button-kit menu-button-kit-nav w-nav-button">
          <img src="{% static 'images/Menu-Icon_1Menu-Icon.png'%}" height="14" width="20" alt="" class="menu-icon-kit-nav">
          <img src="{% static 'images/Menu-Icon_1Menu-Icon.png'%}" height="14" width="20" alt="" class="menu-icon-swipe">
        </div>
    </div>

</div>
    <!-- Base에 추가할 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- Base에 추가할 내용 End-->

    <!-- 부트스트랩 JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Webflow JS-->
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fdf5b16ab6df35ee79b9f8e" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{% static 'js/webflow.js'%}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({  google: {    families: ["Work Sans:100,200,300,regular,500,600,700,800,900"]  }});</script>
    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
    
    {% block script %}
    {% endblock %}
</body>
</html>

main_app/templates/footer.html
{% load static %}
<div class="wrapper login">
    <div class="footer1 login">
      <div class="section footer_top">
        <div class="w-layout-grid footer1-grid">
          <div class="div-block">
            <a href="{% url 'main'%}" aria-current="page" class="size3-link w--current">Sand Box<br></a>
            <div class="text-block-6">전자 및 정보공학과 비교과 웹</div>
          </div>
          <div id="w-node-bd16c739f7f1-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">전체비교과</div>
            <a href="{% url 'dsum'%}" class="footer1-link">- D-sum</a>
            <a href="{% url 'QnA_app:QnA_main'%}" class="footer1-link">- 전공1000제</a>
            <a href="{% url 'tutoring'%}" class="footer1-link">- 전공튜터링</a>
            <a href="#" class="footer1-link">- 공모전</a>
          </div>
          <div id="w-node-5bf0e6eb928c-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">기타</div>
            <a href="#" class="footer1-link">- Coworking</a>
            <a href="#" class="footer1-link">- 과학문화활동</a>
            <a href="#" class="footer1-link">- Data Refinery</a>
            <a href="#" class="footer1-link">- SFRG 링크연구회</a>
            <a href="#" class="footer1-link">- 캡스톤 프로그램</a>
            <a href="#" class="footer1-link">- Super Computing Center</a>
          </div>
          <div id="w-node-207532bb1fb3-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text">Pages</div>
            <a href="https://sejong.korea.ac.kr/kr" target="_blank" class="footer1-link">- 고려대학교 세종캠퍼스</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/index.do" target="_blank" class="footer1-link">- 전자 및 정보공학과</a>
            <a href="https://sportal.korea.ac.kr/" target="_blank" class="footer1-link">- 인재양성통합관리시스템</a>
            <a href="#" class="footer1-link">- KUHAS</a>
          </div>
          <div id="w-node-f97fb593708e-c739f7eb" class="footer1-links-wrap">
            <div class="size6-text"> </div>
            <a href="https://sejong.korea.ac.kr/personal_information_policy" class="footer1-link">- 개인정보처리방침</a>
            <a href="https://sejong.korea.ac.kr/refusal_of_receiving_emails" class="footer1-link">- 이메일주소 무단수집거부</a>
            <a href="https://sejong.korea.ac.kr/mbshome/mbs/kueie/subview.do?id=kueie_010400000000" class="footer1-link">- 찾아오시는길</a>
          </div>
        </div>
      </div>
    </div>
    <div class="section footer_bottom">
      <div class="w-layout-grid footer1-bottom-grid">
        <div id="w-node-bd16c739f81b-c739f7eb">
          <div class="text-block-7">[30019] 세종특별자치시 세종로 2511 고려대학교 세종캠퍼스 과학기술1관 111B호</div>
          <div class="text-block-7 tel">TEL : 044-860-1350</div>
          <div class="text-block-7">Copyright ⓒ KOREA University Sejong Campus. All Rights Reserved | product by KUHAS</div>
        </div>
        <div id="w-node-bd16c739f81e-c739f7eb">
          <div class="nav-kit-wrap"><img src="{% static 'images/crimson1positive.gif'%}" loading="lazy" width="23" alt="" class="image-2">
            <a href="#" class="prospero-brand w-nav-brand">
              <div class="prospero-nav-logo"><span class="text-span"><strong class="bold-text">고려대학교 세종캠퍼스</strong></span></div>
              <div class="prospero-nav-logo under"><strong class="bold-text-3">KOREA UNIVERSITY SEJONG CAMPUS</strong></div>
            </a>
            <div class="nav-kit-divider"></div>
          </div>
        </div>
      </div>
    </div>
  </div>