QnA_app/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views, comment_views

app_name = 'QnA_app'

urlpatterns = [
    # base_views.py
    path('', base_views.QnA_main, name="QnA_main"),
    path('detail/<int:pk>', base_views.detail, name="QnA_detail"),

    # question_views.py
    path('post/', question_views.post, name="post"),
    path('question/update/<int:pk>', question_views.question_update, name="question_update"),
    path('delete/<int:pk>', question_views.question_delete, name="question_delete"),

    # answer_views.py
    path('answer/<int:pk>', answer_views.answer_create, name='answer_create'),
    path('answer/update/<int:answer_id>/', answer_views.answer_update, name='answer_update'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:pk>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'), 
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

basic/urls.py
from django.contrib import admin
from django.urls import path, include
import main_app.urls

import login_app.urls

import QnA_app.urls
from QnA_app.views import base_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(main_app.urls)),
    
    path('', base_views.QnA_main, name="QnA_main"),
    path('QnA/', include(QnA_app.urls)),
    path('common/', include(login_app.urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

QnA_app/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
 #Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=30)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ["category_name"]
    
    def __str__(self):
        return self.category_name

class QnaModel(models.Model):
   author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
   title = models.CharField(max_length=100, null=False)
   content = RichTextUploadingField(null=False)
   created_date = models.DateTimeField(auto_now_add=True)
   modified_date = models.DateTimeField(null=True, blank=True)
   hits = models.PositiveIntegerField(default = 0)
   category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

   def __str__(self):
      return self.title
   
   @property
   def counter(self):
      self.hits = self.hits + 1
      self.save()

class Answer(models.Model):
   author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
   question = models.ForeignKey(QnaModel, on_delete=models.CASCADE)
   content = RichTextUploadingField(null=False)
   created_date = models.DateTimeField(auto_now_add=True)
   modified_date = models.DateTimeField(null=True, blank=True)

class Comment(models.Model):
   author = models.ForeignKey(User, on_delete=models.CASCADE)
   content = models.TextField()
   created_date = models.DateTimeField()
   modified_date = models.DateTimeField(null=True, blank=True)
   question = models.ForeignKey(QnaModel, null=True, blank=True, on_delete=models.CASCADE)
   answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

QnA_app/forms.py
from django import forms
from .models import QnaModel, Answer, Comment
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class New(forms.ModelForm):
    class Meta:
        model = QnaModel
        fields = ['category', 'title', 'content']

    widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control', 'style': 'width: 200%', 'placeholder': '제목을 입력하세요.'}
            ),
            'content': forms.CharField(widget=CKEditorUploadingWidget()),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
       model = Answer
       fields = ['content']
       labels = {
       'content' : '답변내용',
       }
    widgets = {
        'content': forms.CharField(widget=CKEditorUploadingWidget()),
    }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

QnA_app/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import QnaModel, Answer
from ckeditor.widgets import CKEditorWidget

@login_required(login_url='login_app:login')
def answer_create(request, pk):
    question = get_object_or_404(QnaModel, pk=pk)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.created_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('QnA_app:QnA_detail', pk=pk), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'QnA/QnA_detail.html', context)

@login_required(login_url='login_app:login')
def answer_update(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('QnA_app:QnA_detail', pk=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modified_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('QnA_app:QnA_detail', pk=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'QnA/QnA_answer_update.html', context)

@login_required(login_url='login_app:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('QnA_app:QnA_detail', pk=answer.question.id)

QnA_app/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import QnaModel

def QnA_main(request):
    """
    paginator
    """
    # 입력 parameter
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recent':
        boards = QnaModel.objects.order_by('-created_date')
    elif so == 'author':
        boards = QnaModel.objects.order_by('author', '-created_date')
    else:  # popular
        boards = QnaModel.objects.order_by('-hits')
    
    #------------------------------------------------------------------------#
    # 검색
    if kw:
            boards = boards.filter(
                Q(title__icontains=kw)  # 제목검색
                #Q(content__icontains=kw) |  # 내용검색
                #Q(author__username__icontains=kw) |  # 질문 글쓴이검색
                #Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색 
            ).distinct()
    #------------------------------------------------------------------------#

    # 페이징 처리
    paginator = Paginator(boards, 10) # 게시글 10개
    page_obj = paginator.get_page(page)

    context = {'boards': page_obj, 'page': page, 'kw': kw, 'so': so}  # page와 search가 추가되었다.
    # boards = QnaModel.objects.all()
    return render(request, 'QnA/QnA_main.html', context)

def detail(request, pk):
    try:
        boards = get_object_or_404(QnaModel, pk=pk)
    except QnaModel.DoesNotExist:
        raise Http404("Does not exist!")
    boards.counter
    return render(request, 'QnA/QnA_detail.html', {'boards': boards})

QnA_app/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import QnaModel, Answer, Comment

@login_required(login_url='login_app:login')
def comment_create_question(request, pk):
    question = get_object_or_404(QnaModel, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.created_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('QnA_app:QnA_detail', pk=question.id),
                comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'QnA/comment_form.html', context)

@login_required(login_url='login_app:login')
def comment_modify_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', pk=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modified_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('QnA_app:QnA_detail', pk=comment.question.id),
                comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'QnA/comment_form.html', context)

@login_required(login_url='login_app:login')
def comment_delete_question(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('QnA_app:QnA_detail', pk=comment.pk)
    else:
        comment.delete()
    return redirect('QnA_app:QnA_detail', pk=comment.pk)

@login_required(login_url='login_app:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.created_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('QnA_app:QnA_detail', pk=comment.answer.question.id),
                comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'QnA/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('QnA_app:QnA_detail', pk=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modified_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('QnA_detail', pk=comment.answer.question.id),
                comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'QnA/comment_form.html', context)


@login_required(login_url='login_app:login')
def comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('QnA_detail', pk=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('QnA_detail', pk=comment.answer.question.id)

QnA_app/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import New
from ..models import QnaModel

@login_required(login_url='login_app:login')
def post(request):
    if request.method == 'POST':
        form = New(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.created_date = timezone.now()
            question.save()
            return redirect('QnA_app:QnA_main')
    else:
        form = New()
    context = {'form': form}
    return render(request, 'QnA/QnA_post.html', context)
    
@login_required(login_url='login_app:login')
def question_update(request, pk):
    question = get_object_or_404(QnaModel, pk=pk)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('QnA_app:QnA_detail', pk=question.id)

    if request.method == "POST":
        form = New(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modified_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('QnA_app:QnA_detail', pk=question.id)
    else:
        form = New(instance = question)
    context = {'form': form}
    return render(request, 'QnA/QnA_question_update.html', context)

@login_required(login_url='login_app:login')
def question_delete(request, pk):
    question = get_object_or_404(QnaModel, pk=pk)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('QnA/QnA_detail.html', pk=question.id)
    question.delete()
    return redirect('QnA_app:QnA_main')

QnA_app/templates/QnA/QnA_detail.html
{% load QnA_filter %}

<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'main' %}">비교과 홈페이지</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
              {% if user.is_authenticated %}
              <h5>{{ user.username }}</h5>
                <a class="nav-link" href="{% url 'login_app:logout' %}">로그아웃</a>
              {% else %}
                <a class="nav-link" href="{% url 'login_app:login' %}">로그인</a>
              {% endif %}
            </li>
        </ul>
    </div>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            전체비교과 
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'dsum' %}">D-SUM</a>
          <a class="dropdown-item" href="{% url 'contest' %}">공모전</a>
          <a class="dropdown-item" href="{% url 'tutoring' %}">전공튜터링</a>
          <a class="dropdown-item" href="{% url 'QnA_main' %}">1000제 문제 QnA</a>
        </div>
    </div>
</nav>

{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>QnA 게시판 - {{ boards.title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'QnA_app:QnA_main' %}" class="navbar-brand d-flex align-items-center">
                <strong>QnA 게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ boards.title }}</h5>
            <p class="card-text"><small class="text-muted">{{ boards.created_date | date:"Y-m-d H:i" }} 조회수 : {{boards.hits}} </small></p>
            <p class="card-text">{{ boards.content|mark }}</p>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                <div class="mb-2">{{ boards.author.username }}</div>
                <div>{{ boards.created_date }}</div>
                   {% if boards.modified_date %}
                    <div class="badge badge-light p-2 text-left mx-3">
                        <div class="mb-2">수정됨</div>
                        <div>{{ boards.modified_date }}</div>
                    </div>
                    {% endif %}
                </div>
             </div>

                 <!-- 질문 댓글 Start -->
            {% if boards.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in boards.comment_set.all %}
            <a name="comment_{{ comment.id }}"></a>
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.created_date }}
                        {% if comment.modified_date %}
                        (수정:{{ comment.modified_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'QnA_app:comment_modify_question' comment.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete" 
                    data-uri="{% url 'QnA_app:comment_delete_question' comment.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'QnA_app:comment_create_question' boards.id  %}" 
                class="small"><small>댓글 추가 ..</small></a>
            </div>
            <!-- 질문 댓글 End -->
        </div>
    </div>

    {% if request.user == boards.author %}
        <div class="row mt-3">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                    <a class="btn btn-info" href="{% url 'QnA_app:question_update' boards.id %}" role="button">수정</a>
            </div>
            <div class="col-auto">
                <form id="delete-form" action="{% url 'QnA_app:question_delete' boards.id %}" method="post">
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'QnA_app:question_delete' boards.id  %}">삭제</a>
                </form>
            </div>
        </div>
    {%endif%}
    <br><br>
    <!-- 답변 개수 알림 -->
    <h5>{{ boards.answer_set.count }}개의 답변이 있습니다.</h5>
    <div>
        <ul>
        {% for answer in boards.answer_set.all %}
        <a name="answer_{{ answer.id }}"></a>
            <li>
            <div class="card my-3">
                <div class="card-body" enctype="multipart/form-data">
                    {{ form.media }}
                    {{ form.as_p }}
                    {{ answer.content|mark }}
                    <div class="card-text" style="white-space: pre-line;">
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ answer.author.username }}</div>
                        <div>{{ answer.created_date }}</div>
                         {% if answer.modified_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">수정됨</div>
                            <div>{{ answer.modified_date }}</div>
                        </div>
            {% endif %}
                    </div>
                    {% if request.user == answer.author %}
                        <div class="my-3">
                            <a href="{% url 'QnA_app:answer_update' answer.id  %}" 
                            class="btn btn-sm btn-outline-secondary">수정</a>
                             <a href="#" class="delete btn btn-sm btn-outline-secondary " 
                                data-uri="{% url 'QnA_app:answer_delete' answer.id  %}">삭제</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            </li>
        
        <!-- 답변 댓글 시작-->
        {% if answer.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            <a name="comment_{{ comment.id }}"></a>
                <div class="comment py-2 text-muted">
                    <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                        <!--{{ comment.content }}-->
                        {{ form.media }}
                        {{ form.as_p }}
                    </form>
                    <span>
                        - {{ comment.author }}, {{ comment.created_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'QnA_app:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete" 
                    data-uri="{% url 'QnA_app:comment_delete_answer' comment.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <div>
            <a href="{% url 'QnA_app:comment_create_answer' answer.id  %}" 
               class="small"><small>댓글 추가 ..</small></a>
        </div>
        <!-- 답변 댓글 끝-->
        {% endfor %}
        </ul>
    </div>
    <form action="{% url 'QnA_app:answer_create' boards.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" cols="95" rows="5"></textarea>
        </div>
        <input type="submit" value="답변등록">
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>

<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>

</html>

QnA_app/templates/QnA/Sidebar.html
<!-- Sidebar  -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group">
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light " href="">EIEN220</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light " href="">EIEN221</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light " href="">EIEN222</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light " href="">EIEN223</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light " href="">EIEN224</a>
    </div>
</nav>
</link>

QnA_app/templates/QnA/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'main' %}">비교과 홈페이지</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
              {% if user.is_authenticated %}
              <h5>{{ user.username }}</h5>
                <a class="nav-link" href="{% url 'login_app:logout' %}">로그아웃</a>
              {% else %}
                <a class="nav-link" href="{% url 'login_app:login' %}">로그인</a>
              {% endif %}
            </li>
        </ul>
    </div>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            전체비교과 
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'dsum' %}">D-SUM</a>
          <a class="dropdown-item" href="{% url 'contest' %}">공모전</a>
          <a class="dropdown-item" href="{% url 'tutoring' %}">전공튜터링</a>
          <a class="dropdown-item" href="{% url 'QnA_main' %}">1000제 문제 QnA</a>
        </div>
    </div>
</nav>